# Site settings
title: Fatih Zor - Siber Güvenlik ve Yeni Nesil Teknolojiler
description: "“İnsanlar hayallerinize gülmüyorsa, hayalleriniz yeterince büyük değil demektir.” Robin Sharma"
baseurl: "" 
url: "http://fatihzor.github.io/" 
username: fatihzor
user_title: Fatih Zor - Siber Güvenlik
email: fatihhzor@gmail.com
twitter_username: fatihhzor
github_username:  fatihzor
gplus_username:  FatihZorCE
linkedin_public_url: fatihzor
disqus_username: fatihzor
profile_picture: https://avatars0.githubusercontent.com/FatihZor

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  - title: anasayfa
    url: /
  - title: yazılarım
    url: /posts
  - title: yazı serileri
    url: /series
  - title: etiketler
    url: /tags
  - title: hakkımda
    url: /about
# projects in header index
projects:
  - name: asciilang
    url: https://github.com/victorvoid/asciilang
  - name: vim-frontend
    url: https://github.com/victorvoid/vim-frontend
  - name: generator-capybara
    url: https://github.com/victorvoid/generator-capybara 
# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
